const H={'content-type':'application/json; charset=utf-8','cache-control':'no-store, no-cache, must-revalidate','pragma':'no-cache',};
const json=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:H});
const strip=s=>String(s||'').replace(/<[^>]*>/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/\s+/g,' ').trim();
const domain=u=>{try{return new URL(u).hostname.replace(/^www\./,'')}catch{return ''}};
const tier=u=>/eci\.gov\.in$|information\.up\.gov\.in$|upvidhansabhaproceedings\.gov\.in$|pib\.gov\.in$/.test(domain(u))?1:/indianexpress\.com$|newindianexpress\.com$|moneycontrol\.com$|indiatoday\.in$|ndtv\.com$|news18\.com$/.test(domain(u))?2:3;
async function fetchJson(url){const r=await fetch(url,{headers:{'user-agent':'VANDIRA-UP-2027/STEP100'}});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}
async function fetchText(url){const r=await fetch(url,{headers:{'user-agent':'VANDIRA-UP-2027/STEP100'}});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.text()}
function rss(xml){return [...String(xml).matchAll(/<item>([\s\S]*?)<\/item>/gi)].map(m=>{const x=m[1],g=n=>{const z=x.match(new RegExp(`<${n}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${n}>`,'i'));return z?strip(z[1]):''};const url=g('link')||g('guid');return {title:g('title'),summary:g('description'),url,published_at:g('pubDate')||null,source:domain(url),tier:tier(url)}}).filter(x=>x.title&&x.url)}
async function collect(request){const out=[];try{const d=await fetchJson(new URL('/api/up-politics-feed',request.url));for(const x of (d.items||d.results||[]).slice(0,20)){const url=x.source_url||x.url;out.push({type:'political_news',title:x.headline||x.title,summary:x.summary||x.description||'',url,published_at:x.published_at||null,source:x.source||domain(url),tier:Number(x.source_tier||2),official:false,live:true})}}catch(e){}
try{const xml=await fetchText('https://news.google.com/rss/search?q='+encodeURIComponent('Uttar Pradesh politics election government')+'&hl=en-IN&gl=IN&ceid=IN:en');out.push(...rss(xml).slice(0,15).map(x=>({...x,type:'political_news',discovery:true,live:true})))}catch(e){}
for(const topic of ['government','eci','assembly']){try{const d=await fetchJson(new URL('/api/official-sources?topic='+topic+'&q='+encodeURIComponent('latest Uttar Pradesh '+topic),request.url));for(const x of (d.links||[]).slice(0,6))out.push({type:topic==='eci'?'election_update':topic==='assembly'?'assembly_update':'government_update',title:x.title,summary:'Official source link surfaced by the connector.',url:x.url,published_at:null,source:x.source,tier:1,official:true,live:true})}catch(e){}}
const seen=new Set();return out.filter(x=>{const k=(x.url||x.title).toLowerCase().replace(/\/$/,'');if(!k||seen.has(k))return false;seen.add(k);return true}).slice(0,45)}
async function digest(s){const data=new TextEncoder().encode(String(s));if(globalThis.crypto?.subtle){const b=await crypto.subtle.digest('SHA-256',data);return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}return String(s).length+'-'+String(s).slice(0,40)}
function importance(x){const t=(x.title+' '+x.summary).toLowerCase();let score=x.tier===1?45:x.tier===2?30:10;const critical=/(election commission|polling|election date|model code|cabinet decision|ordinance|court order|resignation|appointed|results|by-election)/i.test(t);const high=/(seat sharing|alliance|bjp|samajwadi|congress|chief minister|deputy chief minister|candidate|assembly|2027|2024)/i.test(t);if(critical)score+=40;else if(high)score+=20;return score>=75?'critical':score>=55?'high':score>=35?'medium':'low'}
function key(x){return `${x.type}|${String(x.url||'').toLowerCase()}|${String(x.title||'').toLowerCase().replace(/\s+/g,' ').trim()}`}
async function enrich(items){return Promise.all(items.map(async x=>({...x,fingerprint:await digest(key(x)),severity:importance(x),verification_state:x.tier===1?'official_source':'reported_or_discovery'})))}
function compare(current,baseline=[]){const old=new Set((baseline||[]).map(x=>x.fingerprint||x.url||key(x)));return current.filter(x=>!old.has(x.fingerprint)&&!old.has(x.url)).sort((a,b)=>({critical:4,high:3,medium:2,low:1}[b.severity]||0)-({critical:4,high:3,medium:2,low:1}[a.severity]||0));}
async function kvGet(env,key){try{return env?.VANDIRA_MONITOR_KV?await env.VANDIRA_MONITOR_KV.get(key,'json'):null}catch{return null}}
async function kvPut(env,key,value){try{if(env?.VANDIRA_MONITOR_KV)await env.VANDIRA_MONITOR_KV.put(key,JSON.stringify(value),{expirationTtl:60*60*24*14});}catch{}}
export async function onRequestOptions(){return new Response(null,{status:204,headers:H})}
export async function onRequestGet({request,env}){return run(request,env,{},'get')}
export async function onRequestPost({request,env}){let p={};try{p=await request.json()}catch{}return run(request,env,p,'post')}
async function run(request,env,p,method){const ac=Number(p.ac_no||p.ac||0)||null;const scope=ac?`ac:${ac}`:'state';const current=await enrich(await collect(request));let baseline=Array.isArray(p.baseline)?p.baseline:[];let persistence='browser_local';if(!baseline.length){const saved=await kvGet(env,`vandira:monitor:${scope}`);if(saved?.signals){baseline=saved.signals;persistence='kv'}}const changes=compare(current,baseline);const meaningful=changes.filter(x=>x.severity==='critical'||x.severity==='high'||x.tier<=2);const checkedAt=new Date().toISOString();if(method==='post'&&p.save_baseline!==false){await kvPut(env,`vandira:monitor:${scope}`,{checked_at:checkedAt,signals:current.map(x=>({fingerprint:x.fingerprint,url:x.url,title:x.title,type:x.type,severity:x.severity,source:x.source,tier:x.tier,published_at:x.published_at}))});persistence=env?.VANDIRA_MONITOR_KV?'kv':'browser_local';}
return json({ok:true,step:'STEP100',scope,checked_at:checkedAt,current_signal_count:current.length,new_signal_count:changes.length,meaningful_alert_count:meaningful.length,current_signals:current.map(x=>({fingerprint:x.fingerprint,url:x.url,title:x.title,type:x.type,severity:x.severity,source:x.source,tier:x.tier,published_at:x.published_at})),alerts:meaningful.slice(0,15).map(x=>({id:x.fingerprint,type:x.type,title:x.title,summary:x.summary,url:x.url,source:x.source,tier:x.tier,published_at:x.published_at,severity:x.severity,verification_state:x.verification_state,reason:x.tier===1?'Official-source change surfaced; verify the underlying page before treating it as established fact.':'New reported/discovery item; independent verification may be required.',next_check:'Cross-check the source and assess constituency/election relevance before action.'})),all_new:changes.slice(0,30),persistence,guardrails:['No invented events or probabilities','Reported news remains attributed until verified','Duplicate/noise suppression is applied','Sensitive personal attributes are not used for political targeting'],delivery_status:'detection_ready_not_push_delivery'});
}
